# ===================================================================
# SERVER CONFIGURATION
# ===================================================================
server:
  forward-headers-strategy: framework
  port: 8081

# ===================================================================
# SPRING SYSTEM CONFIGURATION
# ===================================================================
spring:
  application:
    name: master

  # ===================================================================
  # MULTI-DATASOURCE & MIGRATION CONFIGURATIONS (PostgreSQL)
  # ===================================================================
  datasource:

    # 3. JMP Database Configuration
    jmp-db:
      jdbc-url: jdbc:postgresql://10.10.15.79:55434/dbhub_jmp
      username: phubadm
      password: zerosugar
      driver-class-name: org.postgresql.Driver
      flyway:
        enabled: true        # Set to true to execute migrations on Testing DB on startup
        locations: classpath:db/migration/jmp

    # 4. Wilayah Database Configuration
    wilayah-db:
      jdbc-url: jdbc:postgresql://10.10.15.79:55434/dbhub_jmp
      username: phubadm
      password: zerosugar
      driver-class-name: org.postgresql.Driver
      flyway:
        enabled: true        # Set to true to execute migrations on Wilayah DB on startup
        locations: classpath:db/migration/wilayah
        table: flyway_wilayah_history
        default-schema: wilayah


# ===================================================================
# SYSTEM LOGGING CONFIGURATION
# ===================================================================
logging:
  config: classpath:config/logback-spring.xml

# ===================================================================
# SWAGGER / OPENAPI DOCUMENTATION CONFIGURATION
# ===================================================================
springdoc:
  show-actuator: false       # Set to true if spring-boot-starter-actuator is used
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  version: 1.0.0
  title: Master Service API
  description: Master Service API Documentation
  contact:
    name: Pancaran System
    email: robby.ari@pancaran-logistic.id